title: This is a Jekyll page.
description: This is a description.
baseurl: ""
url: "" #
twitter_username: zenithkun
github_username:  zenithkun

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
